### ISSUE TITLE
Support for multidimensional data

### ISSUE THREAD

**Issue by jnahlers** [andgoldschmidt/derivative#21]
Hi there, great library. Are you thinking of adding support for multivariate data at all?

**Comment by andgoldschmidt** [comment]
The project is focused on providing access to a variety of numerical differentiation schemes for time series data. This time series data can have any number of dimensions, and, for example, two-dimensional movies can be flattened and treated as a time series of vectors.

Alternatively, you can imagine adapting this to two-dimensional data without time. If you want a directional derivative, $D_u f(x, y) = \nabla f \cdot u$, then you can first treat your two-dimensional data as snapshots of the y-axis traversing the x-axis. This computes $\partial_x$. Do the opposite for $\partial_y$.

Let me know if I have understood you correctly.
