### ISSUE TITLE
Git tag version releases

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [andgoldschmidt/derivative#29]
Hey Andy, I'm trying to bump the requirement specifier for `pysindy` and looking for the first release that has a particular code change.  The git repo only has tags for 0.3.1 and 0.4.2.  Not sure what your release workflow is, but could you add a git tag when you release?

**Comment by andgoldschmidt** [comment]
Working on adding CI/CD with GitHub actions and poetry to resolve this. The test action under development has a `poetry install` that takes ~10 min., and it's unclear to me why. This might be another point in favor of Issue #27.

**Comment by andgoldschmidt** [comment]
CI added in #31, CD for releases is still TODO. Regarding the previous comment, I found that `poetry install` was too slow unless the `poetry.lock` file was committed.

**Comment by Jacob-Stevens-Haas** [comment]
Awesome, thanks Andy!  Congrats on the CI!
