### ISSUE TITLE
Hyperparamter optimization plugins?

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [andgoldschmidt/derivative#38]
Hey Andy, I've been trying out a few hyper-parameter optimization methods for Kalman smoothing from recent papers.  While this isn't as established as the main methods of `derivative`, I'd love to be able to rely on this package for the main Kalman parts.

It feels like this would be best as an [entry point](https://setuptools.pypa.io/en/latest/userguide/entry_point.html).  Entry points are a form of [Dependency Inversion](https://en.wikipedia.org/wiki/Dependency_inversion_principle).  That way, users (like me) could write the hyperparameter optimization code in a somewhat throw-away fashion, and `derivative` could call that code with only a few generic lines added to this package.  No need to review code or determine whether an algorithm meets some acceptability criteria.

Not sure if you've grappled with this kind of a programming problem or architecture in the past, but I could draft a quick PR to show how it works?

**Comment by andgoldschmidt** [comment]
Sure. I agree that `derivative` would probably benefit from a hyperparameter optimization suite, but maintaining a bunch of new algorithms is baggage we might not want to carry, so this sounds like the right solution.

The current github test action is failing with this new feature. After I get that sorted, we can add this.

**Comment by Jacob-Stevens-Haas** [comment]
Yeah, I think it's something about either the `install-poetry` action, or how the poetry frontend is saving the metadata on entry points.  On my end, `pip install .[dev]`, `pytest` passes all tests.

I'm going to see if I can troubleshoot it with some more commits.
