### ISSUE TITLE
Differentiation in arrays where len(X.shape)>2?

### ISSUE THREAD

**Issue by yb6599** [andgoldschmidt/derivative#40]
Pertaining to this [issue](https://github.com/dynamicslab/pysindy/issues/472),

While trying to differentiate an array with `len(X.shape) = 3`, for example `X.shape = (10, 100, 2)` and `t = np.arange(0, 10, 0.1)`, since X is not 2-dimensional, I get the error "Invalid Shape of X".
Without having to manipulate the shape of X, is it possible to implement differentiation of multidimensional arrays?

**Comment by andgoldschmidt** [comment]
It should be possible. The `_align_axes(X, t, axis)` and `_restore_axes(dX, axis, flat)` [routines in `differentiation.py`](https://github.com/andgoldschmidt/derivative/blob/f0d566dc6b839a0088da322180924da187557d58/derivative/differentiation.py#L229-L256) can likely be adapted in a way that would enable the derived dimension to be any axis.

In the current version, the indices are arranged into `batch x time`, and the[ default behavior of derivative](https://github.com/andgoldschmidt/derivative/blob/f0d566dc6b839a0088da322180924da187557d58/derivative/differentiation.py#L176-L201) is to loop over each batch dimension. This doesn't leverage vectorization or multithreading, so it's not really performant. But, a possible minimal change would be to reshape internally into `batch x time` and then back into the original shape after the computation.
