### ISSUE TITLE
License is missing from the repository and the pypi source tarball

### ISSUE THREAD

**Issue by moorepants** [andgoldschmidt/derivative#6]
It is typical to package a license file with the distributed source code. It would be helpful for downstream packaging, for example.

**Comment by andgoldschmidt** [comment]
Thanks for noting this. The license should be fixed with b6cacc3b403805a04be64f9a8199e3fb9a0a21a3 (license moved to top level) and 7ccb4b75248cd02eb0eef8dcbb3351697b7600cf (v0.3.1).
